### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by akouSDN** [RDelg/OF-BW-Control#1]
Hi Mr. Rene Delgado,
can you give me a tutorial how to work.

Regards

**Comment by RDelg** [comment]
Hi,

I wrote a tutorial this morning.
This doesn't explain how it works but you can use it to run the code at least.
In the next days I will write something better.

Regards.

**Comment by akouSDN** [comment]
Many thanks Mr. Rene Delgado, waiting for your tutorial. Basically, now I am working on periodic/dynamic per-host bandwidth allocation based on some network parameters in RYU. I hope that your code can help me.

Regards,

**Comment by RDelg** [comment]
Hi,

I wrote a little more. Tell me if you have any question.
https://github.com/RDelg/OF-BW-Control/wiki/Tutorial

**Comment by akouSDN** [comment]
Ok many thanks
