### ISSUE TITLE
Assign a specific amount of BW for each Host at each time

### ISSUE THREAD

**Issue by akouSDN** [RDelg/OF-BW-Control#4]
Hi @RDelg 
I hope that you are doing fine and great.

Please, I want to assigne a specific value for each connected host at each time, and install it in the mater table of the switch.

For example, I have 6 hosts connected to the CPqD switch. I want to assign (based on my bw algorithm) for each client an amount of bw form the total available bw. Let say, at t = 4s, the available bw = 5mbps. 
Host 1 : bw = 1 mbps
Host 2: bw = 750 kbps
Host3: bw = 1.5 mbps
.......

After t = 8s. 
Host 1 : bw = 700 kbps
Host 2: bw = 250kbps
Host3: bw = 1 mbps
.......
So, I want to assign the bw based on my algorithm, and the switch install it in the mater table .

Please, How we can do this in your algorithm. Many thanks

Best Regards,

**Comment by RDelg** [comment]
HI @akouSDN,

I am thinking on run your own algorithm in a new thread which goes to sleep and then wakes up to reallocate the bandwidth:

```
def allocater(self):
    # Allocate bandwidth
    ...
    # Sleep until next timestamp
```

Furthermore, you have to deactivate the feedback from the monitor and `flow_removed_handler`. Also you have to do something with the meter assignment in `_packet_in_handler`.

Regards.

**Comment by akouSDN** [comment]
Thanks @RDelg 
I will try it today and see.

Regards,

**Comment by akouSDN** [comment]
Hi @RDelg 
I hope that you are doing fine.

I have done my rate allocation algorithm, where at each time t recalculate the rate for each client. And I run it as a separate thread in Switch.py. Currently, the algo assign a certain amount of rate for each client at each time. 

This the output for host h4 
`
t = 4s , h4:3936 kbps
........
t = 8s, h4:256 kbps
.......
`

However, I don't understand how we can send this values to the switch and set it in the meter tables. Please can you help me to fix this.

Regards,
Abdelhak

**Comment by RDelg** [comment]
Hi @akouSDN,

I create and modify meters with `_mod_meter_entry` function. For example: suppose that host h1, whose  is MAC 000000000001, has assigned 1000 kbps. If i want to create a meter I would run something like:

```
# creating the meter
...
ofproto = datapath.ofproto
cmd     = ofproto.OFPMC_ADD
meter_id = 123  # a number
rate = 1000     # kbps
self._mod_meter_entry(datapath, cmd, meter_id, rate)
```

And the flow that redirects the traffic to the previous meter:

```
# creating the flow to the meter
....
parser  = datapath.ofproto_parser
meter_id = 123 # same as above
match   = parser.OFPMatch(in_port=in_port, eth_src=src) 
inst    = [parser.OFPInstructionMeter(meter_id), parser.OFPInstructionGotoTable(1)]
mod     = parser.OFPFlowMod(datapath=datapath, priority=priority, match=match, 
                                instructions=inst, table_id=0, idle_timeout=0)
datapath.send_msg(mod)
```

After, if I want to modify the meter I change the`cmd` to `ofproto.OFPMC_MODIFY` and use the specific meter_id that I want to change.

Regards.

**Comment by akouSDN** [comment]
Many thanks @RDelg, I am working on it.
I hope that I can finish it as soon.

Regards,
